# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - FrontendAntivirusAzure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: Windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Create deployment package
        run: |
          # Crear carpeta para deployment
          mkdir deployment-package
          
          # Copiar archivos necesarios
          Copy-Item -Path "build" -Destination "deployment-package/build" -Recurse -ErrorAction SilentlyContinue
          Copy-Item -Path "public" -Destination "deployment-package/public" -Recurse -ErrorAction SilentlyContinue
          Copy-Item -Path "app" -Destination "deployment-package/app" -Recurse -ErrorAction SilentlyContinue
          Copy-Item -Path "package.json" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path "package-lock.json" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path "vite.config.ts" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path "tsconfig.json" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path "tailwind.config.*" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path "postcss.config.*" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path ".env*" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          Copy-Item -Path "web.config" -Destination "deployment-package/" -ErrorAction SilentlyContinue
          
        shell: powershell
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package

  deploy:
    runs-on: Windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_89FB1FF0E3CB43F0A38332F8BA3CA8BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DEC52EF86F6F444585B1FA141E7D9570 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4F6EC5F3528641908FB7A6E12439A5C1 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FrontendAntivirusAzure'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .